(function(){'use strict';
const sidebar=document.getElementById('directory-sidebar'),scrim=document.getElementById('sidebar-scrim'),content=document.getElementById('content-shell'),preview=document.getElementById('media-preview'),toast=document.getElementById('browse-toast'),browseMain=document.getElementById('browse-main'),manager=document.getElementById('curation-manager'),manageButton=document.getElementById('manage-context'),contextNav=document.getElementById('browse-context-nav');let timer,activeSidebarMode='directories';const browseBreadcrumb=contextNav.innerHTML;
function notify(message){toast.textContent=message;toast.hidden=false;clearTimeout(timer);timer=setTimeout(()=>toast.hidden=true,2200)}
function sidebarOpen(open){sidebar.classList.toggle('open',open);scrim.classList.toggle('open',open)}
document.getElementById('open-sidebar').addEventListener('click',()=>sidebarOpen(true));document.getElementById('close-sidebar').addEventListener('click',()=>sidebarOpen(false));scrim.addEventListener('click',()=>sidebarOpen(false));
const panelTitles={directories:'目录',tags:'标签',people:'人物'};
const managerCopy={tags:{title:'管理标签',description:'统一维护标签名称和媒体关系，不会修改或删除原始媒体。'},people:{title:'管理人物',description:'命名、合并和复核相似人脸组，所有决定都由用户确认。'}};
function selectSidebarMode(mode){activeSidebarMode=mode;document.querySelectorAll('[data-sidebar-mode]').forEach(item=>{const active=item.dataset.sidebarMode===mode;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))});document.querySelectorAll('[data-sidebar-panel]').forEach(panel=>panel.hidden=panel.dataset.sidebarPanel!==mode);document.getElementById('sidebar-panel-title').textContent=panelTitles[mode];document.getElementById('drawer-panel-title').textContent=panelTitles[mode];manageButton.hidden=mode==='directories';manageButton.innerHTML='<i class="ph ph-sliders-horizontal"></i>管理'+(mode==='tags'?'标签':'人物');if(!manager.hidden&&mode!=='directories')showManagerPanel(mode)}
document.querySelectorAll('[data-sidebar-mode]').forEach(button=>button.addEventListener('click',()=>selectSidebarMode(button.dataset.sidebarMode)));
document.querySelectorAll('.sidebar-collection-list .collection-row').forEach(button=>button.addEventListener('click',()=>{const list=button.closest('.sidebar-collection-list');list.querySelectorAll('.collection-row').forEach(item=>{const active=item===button;item.classList.toggle('active',active);item.setAttribute('aria-pressed',String(active))})}));
function showManagerPanel(mode){const copy=managerCopy[mode];document.getElementById('manager-title').textContent=copy.title;document.getElementById('manager-description').textContent=copy.description;document.querySelectorAll('[data-manager-panel]').forEach(panel=>panel.hidden=panel.dataset.managerPanel!==mode);contextNav.innerHTML='<a href="#"><i class="ph ph-house"></i></a><i class="ph ph-caret-right"></i><a href="#">'+panelTitles[mode]+'</a><i class="ph ph-caret-right"></i><strong>'+copy.title+'</strong>'}
function openManager(){if(activeSidebarMode==='directories')return;preview.hidden=true;content.classList.remove('with-preview');browseMain.hidden=true;manager.hidden=false;content.classList.add('manage-mode');showManagerPanel(activeSidebarMode);sidebarOpen(false)}
function closeManager(){manager.hidden=true;browseMain.hidden=false;content.classList.remove('manage-mode');contextNav.innerHTML=browseBreadcrumb}
manageButton.addEventListener('click',openManager);document.getElementById('close-manager').addEventListener('click',closeManager);
document.querySelectorAll('[data-tree-toggle]').forEach(button=>button.addEventListener('click',()=>{const icon=button.querySelector('i'),open=icon.classList.contains('ph-caret-down');icon.className='ph '+(open?'ph-caret-right':'ph-caret-down');button.setAttribute('aria-label',button.getAttribute('aria-label').replace(open?'收起':'展开',open?'展开':'收起'))}));
document.querySelectorAll('[data-single-choice]').forEach(group=>group.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;group.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));applyFilters()}));
document.getElementById('recursive').addEventListener('click',event=>event.currentTarget.classList.toggle('active'));
const directoryFilter=document.getElementById('directory-filter');directoryFilter.addEventListener('input',applyFilters);
function applyFilters(){const q=directoryFilter.value.trim().toLocaleLowerCase(),kind=document.querySelector('[data-kind].active')?.dataset.kind||'all';let folders=0,media=0;document.querySelectorAll('[data-filter-name]').forEach(item=>{const visible=!q||item.dataset.filterName.toLocaleLowerCase().includes(q);item.hidden=!visible;if(visible)folders++});document.querySelectorAll('[data-kind-item]').forEach(item=>{const visible=(!q||item.dataset.name.toLocaleLowerCase().includes(q))&&(kind==='all'||item.dataset.kindItem===kind);item.hidden=!visible;if(visible)media++});document.getElementById('folder-count').textContent=String(folders);document.getElementById('media-count').textContent='已载入 '+media+' 项'}
document.querySelectorAll('.current-media').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.current-media').forEach(item=>item.classList.toggle('selected',item===card));document.getElementById('preview-name').textContent=card.dataset.name;preview.hidden=false;content.classList.add('with-preview')}));
document.getElementById('close-preview').addEventListener('click',()=>{preview.hidden=true;content.classList.remove('with-preview')});
document.querySelector('.refresh-button').addEventListener('click',()=>notify('当前目录已刷新'));
document.querySelectorAll('[data-ai-tag]').forEach(button=>button.addEventListener('click',()=>{const accepted=button.classList.toggle('accepted'),label=button.textContent.trim();button.innerHTML=label+' <i class="ph ph-'+(accepted?'check':'plus')+'"></i>';notify(accepted?'建议已由你确认并加入人工标签':'已撤销这次标签确认')}));
const newTagForm=document.getElementById('new-tag-form'),newTagName=document.getElementById('new-tag-name');document.getElementById('new-tag').addEventListener('click',()=>{newTagForm.hidden=false;newTagName.focus()});document.getElementById('cancel-new-tag').addEventListener('click',()=>{newTagForm.hidden=true;newTagName.value=''});newTagForm.addEventListener('submit',event=>{event.preventDefault();const name=newTagName.value.trim();if(!name)return;newTagForm.hidden=true;newTagName.value='';notify('已创建标签“'+name+'”')});
document.getElementById('tag-manager-filter').addEventListener('input',event=>{const query=event.currentTarget.value.trim().toLocaleLowerCase();document.querySelectorAll('.tag-management-row').forEach(row=>row.hidden=query&&!row.dataset.manageName.toLocaleLowerCase().includes(query))});
document.querySelectorAll('[data-rename-tag]').forEach(button=>button.addEventListener('click',()=>{const input=button.closest('.tag-management-row').querySelector('input');if(input.readOnly){input.readOnly=false;input.focus();input.select();button.textContent='保存'}else{input.readOnly=true;button.textContent='重命名';button.closest('.tag-management-row').dataset.manageName=input.value.trim()||'未命名标签';notify('标签名称已更新')}}));
document.querySelectorAll('[data-merge-tag]').forEach(button=>button.addEventListener('click',()=>notify('已进入标签合并选择，原媒体不会改变')));document.querySelectorAll('[data-delete-tag]').forEach(button=>button.addEventListener('click',()=>notify('删除标签只解除关系，原媒体保持不变')));
document.getElementById('people-manager-filter').addEventListener('input',event=>{const query=event.currentTarget.value.trim().toLocaleLowerCase();document.querySelectorAll('.person-management-card').forEach(card=>card.hidden=query&&!card.dataset.manageName.toLocaleLowerCase().includes(query))});document.querySelectorAll('[data-people-filter]').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.peopleFilter;document.querySelectorAll('[data-people-filter]').forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.person-management-card').forEach(card=>card.hidden=filter!=='all'&&card.dataset.personKind!==filter)}));
const personMessages={rename:'人物名称可以在这里修改',merge:'请选择要并入的已有人物',cover:'请选择一张人脸作为代表头像',create:'从这个相似组建立新人物',assign:'请选择要并入的已有人物',inspect:'已进入样本复核，可移出错误人脸'};document.querySelectorAll('[data-person-action]').forEach(button=>button.addEventListener('click',()=>notify(personMessages[button.dataset.personAction])));
document.querySelectorAll('a[href="#"]').forEach(link=>link.addEventListener('click',event=>event.preventDefault()));
}());
