package architecture_test

import (
	"encoding/json"
	"io/fs"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"
)

const modulePath = "github.com/HappyQuQu/foliopath"

type listedPackage struct {
	ImportPath string
	Imports    []string
}

func TestGoDependencyDirection(t *testing.T) {
	root := repositoryRoot(t)
	command := exec.Command("go", "list", "-json", "./...")
	command.Dir = root
	output, err := command.Output()
	if err != nil {
		t.Fatalf("list Go packages: %v", err)
	}

	decoder := json.NewDecoder(strings.NewReader(string(output)))
	for decoder.More() {
		var current listedPackage
		if err := decoder.Decode(&current); err != nil {
			t.Fatalf("decode go list output: %v", err)
		}
		if !strings.HasPrefix(current.ImportPath, modulePath+"/") {
			continue
		}
		for _, imported := range current.Imports {
			checkDependency(t, current.ImportPath, imported)
		}
	}
}

func TestNoGenericCatchAllGoPackages(t *testing.T) {
	root := repositoryRoot(t)
	command := exec.Command("go", "list", "-f", "{{.ImportPath}}", "./...")
	command.Dir = root
	output, err := command.Output()
	if err != nil {
		t.Fatalf("list Go packages: %v", err)
	}

	for _, importPath := range strings.Fields(string(output)) {
		if !strings.HasPrefix(importPath, modulePath+"/") {
			continue
		}
		parts := strings.Split(strings.TrimPrefix(importPath, modulePath+"/"), "/")
		for _, part := range parts {
			if slices.Contains([]string{"utils", "common", "helpers", "base"}, part) {
				t.Errorf("generic catch-all package is forbidden: %s", importPath)
			}
		}
	}

	if info, err := os.Stat(filepath.Join(root, "pkg")); err == nil && info.IsDir() {
		t.Error("top-level pkg/ requires an accepted external-consumer decision")
	} else if err != nil && !os.IsNotExist(err) {
		t.Fatalf("inspect top-level pkg/: %v", err)
	}
}

func TestWebUsesSingleGeneratedAPIClientBoundary(t *testing.T) {
	root := repositoryRoot(t)
	webSource := filepath.Join(root, "web", "src")
	clientPath := filepath.Join(webSource, "lib", "api", "client.ts")
	generatedPath := filepath.Join(webSource, "lib", "api", "generated", "schema.ts")

	for _, required := range []string{clientPath, generatedPath} {
		if info, err := os.Stat(required); err != nil {
			t.Fatalf("required web API boundary %s: %v", required, err)
		} else if !info.Mode().IsRegular() {
			t.Fatalf("required web API boundary is not a regular file: %s", required)
		}
	}

	if err := filepath.WalkDir(webSource, func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || (filepath.Ext(path) != ".ts" && filepath.Ext(path) != ".tsx") {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		source := string(data)
		relative, err := filepath.Rel(webSource, path)
		if err != nil {
			return err
		}
		inAPIBoundary := strings.HasPrefix(relative, filepath.Join("lib", "api")+string(filepath.Separator))
		if strings.Contains(source, `"openapi-fetch"`) && path != clientPath {
			t.Errorf("%s imports openapi-fetch outside the canonical client", relative)
		}
		if strings.Contains(source, "generated/schema") && !inAPIBoundary {
			t.Errorf("%s imports generated OpenAPI types outside lib/api", relative)
		}
		if strings.Contains(source, "fetch(") && path != clientPath {
			t.Errorf("%s calls fetch outside the canonical client", relative)
		}
		return nil
	}); err != nil {
		t.Fatalf("inspect web API imports: %v", err)
	}

	generated, err := os.ReadFile(generatedPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(generated), "Do not edit this file directly.") {
		t.Error("generated OpenAPI types are missing the generated-file marker")
	}
}

func checkDependency(t *testing.T, source, imported string) {
	t.Helper()
	if !strings.HasPrefix(imported, modulePath+"/") {
		return
	}

	sourceArea := internalArea(source)
	importedArea := internalArea(imported)

	switch sourceArea {
	case "api":
		if slices.Contains([]string{"app", "files", "pathpolicy", "store", "webassets"}, importedArea) {
			t.Errorf("HTTP adapter %s must not import concrete/runtime area %s", source, imported)
		}
	case "pathpolicy":
		t.Errorf("pure path policy %s must not import repository package %s", source, imported)
	case "auth", "library", "catalog", "scanner", "thumbnail", "media", "jobs":
		if slices.Contains([]string{"api", "app", "files", "store", "webassets"}, importedArea) {
			t.Errorf("capability/policy package %s must not import outer area %s", source, imported)
		}
	case "files", "store":
		if slices.Contains([]string{"api", "app", "webassets"}, importedArea) {
			t.Errorf("adapter %s must not import delivery/composition area %s", source, imported)
		}
		if (sourceArea == "files" && importedArea == "store") ||
			(sourceArea == "store" && importedArea == "files") {
			t.Errorf("adapter %s must not import sibling adapter %s", source, imported)
		}
	case "webassets":
		t.Errorf("embedded web assets %s must not import repository package %s", source, imported)
	}

	if strings.HasPrefix(source, modulePath+"/cmd/") && imported != modulePath+"/internal/app" {
		t.Errorf("process entry point %s may import only internal/app, imported %s", source, imported)
	}
}

func internalArea(importPath string) string {
	prefix := modulePath + "/internal/"
	if !strings.HasPrefix(importPath, prefix) {
		return ""
	}
	remainder := strings.TrimPrefix(importPath, prefix)
	return strings.SplitN(remainder, "/", 2)[0]
}

func repositoryRoot(t *testing.T) string {
	t.Helper()
	_, filename, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("resolve architecture test location")
	}
	return filepath.Clean(filepath.Join(filepath.Dir(filename), "..", ".."))
}
