import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import openapiTS, { astToString } from "openapi-typescript";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(scriptDirectory, "..");
const schemaURL = new URL("../../api/openapi.yaml", import.meta.url);
const outputPath = resolve(webRoot, "src/lib/api/generated/schema.ts");
const checkOnly = process.argv.includes("--check");

const header = `/**
 * Generated from api/openapi.yaml by openapi-typescript.
 * Do not edit this file directly.
 */

`;
const ast = await openapiTS(schemaURL, {
  alphabetize: true,
  silent: true,
});
const generated = header + astToString(ast);

if (checkOnly) {
  let current;
  try {
    current = await readFile(outputPath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") {
      throw new Error(
        "generated API contract is missing; run `make generate` and commit the result",
      );
    }
    throw error;
  }
  if (current !== generated) {
    throw new Error(
      "generated API contract is stale; run `make generate` and review the diff",
    );
  }
} else {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated, "utf8");
}
