// Code generated by sqlc. DO NOT EDIT.
// source: auth.sql

package dbgen

import (
	"context"
)

const insertAdministrator = `-- name: InsertAdministrator :one
INSERT INTO users (
    singleton_key,
    username,
    username_key,
    display_name,
    password_hash,
    password_scheme,
    password_parameters,
    auth_version,
    created_at_ms,
    updated_at_ms,
    password_changed_at_ms
) VALUES (
    1,
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    1,
    ?7,
    ?8,
    ?9
)
RETURNING
    id,
    username,
    display_name,
    created_at_ms,
    updated_at_ms
`

type InsertAdministratorParams struct {
	Username            string
	UsernameKey         string
	DisplayName         string
	PasswordHash        string
	PasswordScheme      string
	PasswordParameters  string
	CreatedAtMs         int64
	UpdatedAtMs         int64
	PasswordChangedAtMs int64
}

type InsertAdministratorRow struct {
	ID          int64
	Username    string
	DisplayName string
	CreatedAtMs int64
	UpdatedAtMs int64
}

func (q *Queries) InsertAdministrator(ctx context.Context, arg InsertAdministratorParams) (InsertAdministratorRow, error) {
	row := q.db.QueryRowContext(ctx, insertAdministrator,
		arg.Username,
		arg.UsernameKey,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PasswordScheme,
		arg.PasswordParameters,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
		arg.PasswordChangedAtMs,
	)
	var i InsertAdministratorRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const isAdministratorInitialized = `-- name: IsAdministratorInitialized :one
SELECT EXISTS (
    SELECT 1
    FROM users
    WHERE singleton_key = 1
)
`

func (q *Queries) IsAdministratorInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAdministratorInitialized)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
