// Code generated by sqlc. DO NOT EDIT.
// source: libraries.sql

package dbgen

import (
	"context"
)

const findLibraryIDByNameKey = `-- name: FindLibraryIDByNameKey :one
SELECT id
FROM libraries
WHERE name_key = ?1
`

func (q *Queries) FindLibraryIDByNameKey(ctx context.Context, nameKey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findLibraryIDByNameKey, nameKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findOtherLibraryIDByNameKey = `-- name: FindOtherLibraryIDByNameKey :one
SELECT id
FROM libraries
WHERE name_key = ?1
  AND id <> ?2
`

type FindOtherLibraryIDByNameKeyParams struct {
	NameKey string
	ID      int64
}

func (q *Queries) FindOtherLibraryIDByNameKey(ctx context.Context, arg FindOtherLibraryIDByNameKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, findOtherLibraryIDByNameKey, arg.NameKey, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findOverlappingLibraryID = `-- name: FindOverlappingLibraryID :one
SELECT id
FROM libraries
WHERE root_rel_path = ?1
   OR root_rel_path = ''
   OR ?1 = ''
   OR instr(?1, root_rel_path || '/') = 1
   OR instr(root_rel_path, ?1 || '/') = 1
LIMIT 1
`

func (q *Queries) FindOverlappingLibraryID(ctx context.Context, rootRelPath string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findOverlappingLibraryID, rootRelPath)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getLibrary = `-- name: GetLibrary :one
SELECT
    id,
    name,
    name_key,
    root_rel_path,
    status,
    current_generation,
    created_at_ms,
    updated_at_ms
FROM libraries
WHERE id = ?1
`

func (q *Queries) GetLibrary(ctx context.Context, id int64) (Library, error) {
	row := q.db.QueryRowContext(ctx, getLibrary, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.RootRelPath,
		&i.Status,
		&i.CurrentGeneration,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const insertLibrary = `-- name: InsertLibrary :one
INSERT INTO libraries(
    name,
    name_key,
    root_rel_path,
    status,
    current_generation,
    created_at_ms,
    updated_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    'pending',
    0,
    ?4,
    ?5
)
RETURNING
    id,
    name,
    name_key,
    root_rel_path,
    status,
    current_generation,
    created_at_ms,
    updated_at_ms
`

type InsertLibraryParams struct {
	Name        string
	NameKey     string
	RootRelPath string
	CreatedAtMs int64
	UpdatedAtMs int64
}

func (q *Queries) InsertLibrary(ctx context.Context, arg InsertLibraryParams) (Library, error) {
	row := q.db.QueryRowContext(ctx, insertLibrary,
		arg.Name,
		arg.NameKey,
		arg.RootRelPath,
		arg.CreatedAtMs,
		arg.UpdatedAtMs,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.RootRelPath,
		&i.Status,
		&i.CurrentGeneration,
		&i.CreatedAtMs,
		&i.UpdatedAtMs,
	)
	return i, err
}

const listLibraries = `-- name: ListLibraries :many
SELECT
    id,
    name,
    name_key,
    root_rel_path,
    status,
    current_generation,
    created_at_ms,
    updated_at_ms
FROM libraries
ORDER BY name_key, id
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.QueryContext(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Library{}
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.RootRelPath,
			&i.Status,
			&i.CurrentGeneration,
			&i.CreatedAtMs,
			&i.UpdatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameLibrary = `-- name: RenameLibrary :execrows
UPDATE libraries
SET name = ?1,
    name_key = ?2,
    updated_at_ms = ?3
WHERE id = ?4
`

type RenameLibraryParams struct {
	Name        string
	NameKey     string
	UpdatedAtMs int64
	ID          int64
}

func (q *Queries) RenameLibrary(ctx context.Context, arg RenameLibraryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renameLibrary,
		arg.Name,
		arg.NameKey,
		arg.UpdatedAtMs,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
