// Code generated by sqlc. DO NOT EDIT.

package dbgen

import (
	"database/sql"
)

type ScanIssue struct {
	ID            int64
	ScanRunID     int64
	Code          string
	IssueCount    int64
	SampleRelPath sql.NullString
	CreatedAtMs   int64
}

type ScanRun struct {
	ID                    int64
	LibraryID             int64
	Generation            int64
	TriggerKind           string
	Status                string
	DiscoveredDirectories int64
	DiscoveredAssets      int64
	SkippedCount          int64
	ErrorCode             sql.NullString
	CreatedAtMs           int64
	StartedAtMs           sql.NullInt64
	FinishedAtMs          sql.NullInt64
	Revision              int64
	Phase                 string
	ProcessedAssets       int64
	SkippedDirectories    int64
	SkippedFiles          int64
	ErrorCount            int64
	IssuesTruncated       int64
	CancelRequestedAtMs   sql.NullInt64
	HeartbeatAtMs         sql.NullInt64
	AvailableAtMs         int64
	LeaseExpiresAtMs      sql.NullInt64
	AttemptCount          int64
}

type Setting struct {
	SingletonKey               int64
	ScheduledScanIntervalHours sql.NullInt64
	ThumbnailCacheQuotaBytes   int64
	Language                   string
	Revision                   int64
	UpdatedAtMs                int64
}
