// Code generated by sqlc. DO NOT EDIT.

package dbgen

type Library struct {
	ID                int64
	Name              string
	NameKey           string
	RootRelPath       string
	Status            string
	CurrentGeneration int64
	CreatedAtMs       int64
	UpdatedAtMs       int64
}
