// Code generated by sqlc. DO NOT EDIT.
// source: scans.sql

package dbgen

import (
	"context"
	"database/sql"
)

const cancelQueuedScan = `-- name: CancelQueuedScan :one
UPDATE scan_runs
SET status = 'cancelled',
    phase = 'completed',
    cancel_requested_at_ms = COALESCE(cancel_requested_at_ms, ?1),
    finished_at_ms = ?1,
    revision = revision + 1
WHERE id = ?2
  AND status = 'queued'
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

type CancelQueuedScanParams struct {
	NowMs sql.NullInt64
	ID    int64
}

func (q *Queries) CancelQueuedScan(ctx context.Context, arg CancelQueuedScanParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, cancelQueuedScan, arg.NowMs, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const claimNextQueuedScan = `-- name: ClaimNextQueuedScan :one
UPDATE scan_runs
SET status = 'running',
    phase = 'checking_root',
    started_at_ms = ?1,
    heartbeat_at_ms = ?1,
    lease_expires_at_ms = ?2,
    attempt_count = attempt_count + 1,
    revision = revision + 1
WHERE id = (
    SELECT id
    FROM scan_runs
    WHERE status = 'queued'
      AND cancel_requested_at_ms IS NULL
      AND available_at_ms <= ?1
      AND attempt_count < 3
    ORDER BY available_at_ms, created_at_ms, id
    LIMIT 1
)
  AND status = 'queued'
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

type ClaimNextQueuedScanParams struct {
	NowMs            sql.NullInt64
	LeaseExpiresAtMs sql.NullInt64
}

func (q *Queries) ClaimNextQueuedScan(ctx context.Context, arg ClaimNextQueuedScanParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, claimNextQueuedScan, arg.NowMs, arg.LeaseExpiresAtMs)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const countActiveScans = `-- name: CountActiveScans :one
SELECT COUNT(*)
FROM scan_runs
WHERE status IN ('queued', 'running')
`

func (q *Queries) CountActiveScans(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveScans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findActiveScanForLibrary = `-- name: FindActiveScanForLibrary :one
SELECT id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
FROM scan_runs
WHERE library_id = ?1
  AND status IN ('queued', 'running')
ORDER BY id
LIMIT 1
`

func (q *Queries) FindActiveScanForLibrary(ctx context.Context, libraryID int64) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, findActiveScanForLibrary, libraryID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const getScanContractRun = `-- name: GetScanContractRun :one
SELECT id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
FROM scan_runs
WHERE id = ?1
`

func (q *Queries) GetScanContractRun(ctx context.Context, id int64) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, getScanContractRun, id)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT singleton_key, scheduled_scan_interval_hours, thumbnail_cache_quota_bytes, language, revision, updated_at_ms
FROM settings
WHERE singleton_key = 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.SingletonKey,
		&i.ScheduledScanIntervalHours,
		&i.ThumbnailCacheQuotaBytes,
		&i.Language,
		&i.Revision,
		&i.UpdatedAtMs,
	)
	return i, err
}

const insertQueuedScan = `-- name: InsertQueuedScan :one
INSERT INTO scan_runs(
    library_id,
    generation,
    trigger_kind,
    status,
    phase,
    created_at_ms,
    available_at_ms
) VALUES (
    ?1,
    ?2,
    ?3,
    'queued',
    'queued',
    ?4,
    ?5
)
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

type InsertQueuedScanParams struct {
	LibraryID     int64
	Generation    int64
	TriggerKind   string
	CreatedAtMs   int64
	AvailableAtMs int64
}

func (q *Queries) InsertQueuedScan(ctx context.Context, arg InsertQueuedScanParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, insertQueuedScan,
		arg.LibraryID,
		arg.Generation,
		arg.TriggerKind,
		arg.CreatedAtMs,
		arg.AvailableAtMs,
	)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const listLibraryScanContractRuns = `-- name: ListLibraryScanContractRuns :many
SELECT id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
FROM scan_runs
WHERE library_id = ?1
  AND (
      created_at_ms < ?2
      OR (
          created_at_ms = ?2
          AND id < ?3
      )
  )
ORDER BY created_at_ms DESC, id DESC
LIMIT ?4
`

type ListLibraryScanContractRunsParams struct {
	LibraryID         int64
	BeforeCreatedAtMs int64
	BeforeID          int64
	PageSize          int64
}

func (q *Queries) ListLibraryScanContractRuns(ctx context.Context, arg ListLibraryScanContractRunsParams) ([]ScanRun, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryScanContractRuns,
		arg.LibraryID,
		arg.BeforeCreatedAtMs,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanRun{}
	for rows.Next() {
		var i ScanRun
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Generation,
			&i.TriggerKind,
			&i.Status,
			&i.DiscoveredDirectories,
			&i.DiscoveredAssets,
			&i.SkippedCount,
			&i.ErrorCode,
			&i.CreatedAtMs,
			&i.StartedAtMs,
			&i.FinishedAtMs,
			&i.Revision,
			&i.Phase,
			&i.ProcessedAssets,
			&i.SkippedDirectories,
			&i.SkippedFiles,
			&i.ErrorCount,
			&i.IssuesTruncated,
			&i.CancelRequestedAtMs,
			&i.HeartbeatAtMs,
			&i.AvailableAtMs,
			&i.LeaseExpiresAtMs,
			&i.AttemptCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanIssues = `-- name: ListScanIssues :many
SELECT id, scan_run_id, code, issue_count, sample_rel_path, created_at_ms
FROM scan_issues
WHERE scan_run_id = ?1
ORDER BY id
LIMIT 50
`

func (q *Queries) ListScanIssues(ctx context.Context, scanRunID int64) ([]ScanIssue, error) {
	rows, err := q.db.QueryContext(ctx, listScanIssues, scanRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanIssue{}
	for rows.Next() {
		var i ScanIssue
		if err := rows.Scan(
			&i.ID,
			&i.ScanRunID,
			&i.Code,
			&i.IssueCount,
			&i.SampleRelPath,
			&i.CreatedAtMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextScanGeneration = `-- name: NextScanGeneration :one
SELECT COALESCE(MAX(generation), 0) + 1
FROM scan_runs
WHERE library_id = ?1
`

func (q *Queries) NextScanGeneration(ctx context.Context, libraryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextScanGeneration, libraryID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const recoverNextExpiredScan = `-- name: RecoverNextExpiredScan :one
UPDATE scan_runs
SET status = CASE WHEN attempt_count >= 3 THEN 'interrupted' ELSE 'queued' END,
    phase = CASE WHEN attempt_count >= 3 THEN 'completed' ELSE 'queued' END,
    started_at_ms = CASE WHEN attempt_count >= 3 THEN started_at_ms ELSE NULL END,
    finished_at_ms = CASE WHEN attempt_count >= 3 THEN ?1 ELSE NULL END,
    heartbeat_at_ms = NULL,
    lease_expires_at_ms = NULL,
    available_at_ms = ?1,
    error_code = CASE WHEN attempt_count >= 3 THEN 'scan_interrupted' ELSE NULL END,
    revision = revision + 1
WHERE id = (
    SELECT id
    FROM scan_runs
    WHERE status = 'running'
      AND lease_expires_at_ms <= ?1
    ORDER BY lease_expires_at_ms, id
    LIMIT 1
)
  AND status = 'running'
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

func (q *Queries) RecoverNextExpiredScan(ctx context.Context, nowMs int64) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, recoverNextExpiredScan, nowMs)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const requestRunningScanCancellation = `-- name: RequestRunningScanCancellation :one
UPDATE scan_runs
SET cancel_requested_at_ms = COALESCE(cancel_requested_at_ms, ?1),
    revision = CASE
        WHEN cancel_requested_at_ms IS NULL THEN revision + 1
        ELSE revision
    END
WHERE id = ?2
  AND status = 'running'
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

type RequestRunningScanCancellationParams struct {
	NowMs sql.NullInt64
	ID    int64
}

func (q *Queries) RequestRunningScanCancellation(ctx context.Context, arg RequestRunningScanCancellationParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, requestRunningScanCancellation, arg.NowMs, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const touchScanLease = `-- name: TouchScanLease :one
UPDATE scan_runs
SET heartbeat_at_ms = ?1,
    lease_expires_at_ms = ?2
WHERE id = ?3
  AND status = 'running'
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

type TouchScanLeaseParams struct {
	NowMs            sql.NullInt64
	LeaseExpiresAtMs sql.NullInt64
	ID               int64
}

func (q *Queries) TouchScanLease(ctx context.Context, arg TouchScanLeaseParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, touchScanLease, arg.NowMs, arg.LeaseExpiresAtMs, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const updateRunningScanPhase = `-- name: UpdateRunningScanPhase :one
UPDATE scan_runs
SET phase = ?1,
    revision = revision + 1
WHERE id = ?2
  AND status = 'running'
  AND phase <> ?1
RETURNING id, library_id, generation, trigger_kind, status, discovered_directories, discovered_assets, skipped_count, error_code, created_at_ms, started_at_ms, finished_at_ms, revision, phase, processed_assets, skipped_directories, skipped_files, error_count, issues_truncated, cancel_requested_at_ms, heartbeat_at_ms, available_at_ms, lease_expires_at_ms, attempt_count
`

type UpdateRunningScanPhaseParams struct {
	Phase string
	ID    int64
}

func (q *Queries) UpdateRunningScanPhase(ctx context.Context, arg UpdateRunningScanPhaseParams) (ScanRun, error) {
	row := q.db.QueryRowContext(ctx, updateRunningScanPhase, arg.Phase, arg.ID)
	var i ScanRun
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Generation,
		&i.TriggerKind,
		&i.Status,
		&i.DiscoveredDirectories,
		&i.DiscoveredAssets,
		&i.SkippedCount,
		&i.ErrorCode,
		&i.CreatedAtMs,
		&i.StartedAtMs,
		&i.FinishedAtMs,
		&i.Revision,
		&i.Phase,
		&i.ProcessedAssets,
		&i.SkippedDirectories,
		&i.SkippedFiles,
		&i.ErrorCount,
		&i.IssuesTruncated,
		&i.CancelRequestedAtMs,
		&i.HeartbeatAtMs,
		&i.AvailableAtMs,
		&i.LeaseExpiresAtMs,
		&i.AttemptCount,
	)
	return i, err
}

const updateSettings = `-- name: UpdateSettings :one
UPDATE settings
SET scheduled_scan_interval_hours = ?1,
    thumbnail_cache_quota_bytes = ?2,
    language = ?3,
    revision = revision + 1,
    updated_at_ms = ?4
WHERE singleton_key = 1
  AND revision = ?5
RETURNING singleton_key, scheduled_scan_interval_hours, thumbnail_cache_quota_bytes, language, revision, updated_at_ms
`

type UpdateSettingsParams struct {
	ScheduledScanIntervalHours sql.NullInt64
	ThumbnailCacheQuotaBytes   int64
	Language                   string
	UpdatedAtMs                int64
	ExpectedRevision           int64
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, updateSettings,
		arg.ScheduledScanIntervalHours,
		arg.ThumbnailCacheQuotaBytes,
		arg.Language,
		arg.UpdatedAtMs,
		arg.ExpectedRevision,
	)
	var i Setting
	err := row.Scan(
		&i.SingletonKey,
		&i.ScheduledScanIntervalHours,
		&i.ThumbnailCacheQuotaBytes,
		&i.Language,
		&i.Revision,
		&i.UpdatedAtMs,
	)
	return i, err
}
